sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t stmu/rpi-motioneye .
# test image
#- docker run stmu/rpi-motioneye mysql --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag stmu/rpi-motioneye stmu/rpi-motioneye:latest
    docker push stmu/rpi-motioneye:latest
    docker push stmu/rpi-motioneye
  fi